#!/usr/bin/env bash
bayesed="$1" #e.g. ./bin/linux/bayesed_n|./bin/linux/bayesed_1|./bin/mac/bayesed_n|./bin/mac/bayesed_1
mpirun="$2" # e.g. mpirun|/opt/local/bin/mpirun
nlive=400
efr=0.1
tol=0.5
seed=1
verbose=2
multinest="--multinest 1,0,0,$nlive,$efr,$tol,1000,-1e90,$seed,$verbose,0,0,-1e90,100000,0.01"
time $mpirun $bayesed $multinest  -i 0,observation/test2/test.txt --filters observation/test2/filters.txt --filters_selected observation/test2/filters_selected.txt --ssp 0,0,bc2003_lr_BaSeL_chab,1,3,1,0,0,0,0,0 --sfh 0,2,0,0 --dal 0,2,7 -gb 0,1,gb,-2,1,1,1000,200 -a 1,2,clumpy201410tor,1 --outdir test2 --save_bestfit 0 --save_sample_par
